version: '3.7'

configs:
  telegraf_config:
    file: ./telegraf.conf

services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bzO10KmR8x
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 1g

  telegraf:
    image: "telegraf:latest"
    ports:
      - "4317:4317"
    configs:
      - source: telegraf_config
        target: /etc/telegraf/telegraf.conf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  nats:
    image: "nats:latest"
    command:
      - "-js"
    ports:
      - "4222:4222"
      - "6222:6222"
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "8080:8080"
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=./home/filip/Desktop/cirrina-tracing/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/home/filip/Desktop/cirrina-tracing/loki-config.yaml:ro
      - ./loki-wal:/var/lib/loki/wal
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki:3100
            basicAuth: false
            isDefault: false
            varsion: 1
            editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5001:4317"
      - "5002:4318"
      - "5778:5778"
      - "16686:16686"
      - "6831:6831/udp"
      - "14250:14250"