LINUX_BASE_BOX = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        ip = "10.10.2.10"

        master.vm.box = LINUX_BASE_BOX
        master.vm.hostname = "master"
        master.vm.network "private_network", ip: ip
        master.vm.network "forwarded_port", guest: 6443, host: 6443

        master.vm.provider "virtualbox" do |virtualbox|
            virtualbox.customize ["modifyvm", :id, "--cableconnected1", "on", "--audio", "none"]
            virtualbox.memory = "2048"
            virtualbox.cpus = "2"
        end

        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "./ansible/kubernetes.yml"
            ansible.extra_vars = {
                node_ip: ip,
            }
        end
    end

    # Node VMs
    1.upto(2) do |n|
        config.vm.define "node#{n}" do |node|
            ip = "10.10.2.%d" % [20 + n]

            node.vm.box = LINUX_BASE_BOX
            node.vm.hostname = "node#{n}"
            node.vm.network "private_network", ip: ip

            node.vm.provider "virtualbox" do |virtualbox|
                virtualbox.customize ["modifyvm", :id, "--cableconnected1", "on", "--audio", "none"]
                virtualbox.memory = "2048"
                virtualbox.cpus = "2"
            end

            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "./ansible/kubernetes.yml"
                ansible.extra_vars = {
                    node_ip: ip,
                }
            end
        end
    end
end