---
# Ref: https://www.nomadproject.io/downloads
- name: add hashicorp signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: add hashicorp repository
  apt_repository:
    # NOTE: `ansible_distribution_release` is an Ansible fact
    # Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: install nomad
  apt:
    name: [ "nomad" ]
    update_cache: yes

- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: create /etc/dnsmasq.d/10-consul.conf for Consul DNS
  copy:
    dest: /etc/dnsmasq.d/10-consul.conf
    content: |
      server=/consul/127.0.0.1#8600
    owner: root
    group: root
    mode: '0644'

- name: set up /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver {{ ansible_default_ipv4.address }}
      nameserver 8.8.8.8
    create: yes
    owner: root
    group: root
    mode: '0644'

- name: disable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: enable and start dnsmasq
  systemd:
    name: dnsmasq
    enabled: true
    state: started

- name: restart Docker service
  systemd:
    name: docker
    state: restarted