name: Test
on:
  workflow_run:
    workflows: [ "build" ]
    types: [ "completed" ]
permissions:
  checks: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Reports
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test-reports
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'test-results/test/TEST-*.xml'
          fail_on_failure: true
          require_tests: true
          include_passed: true
          detailed_summary: true
      #- name: JaCoCo Code Coverage Report
      #  uses: PavanMudigonda/jacoco-reporter@v5.0
      #  with:
      #    coverage_results_path: reports/jacoco/test/jacocoTestReport.xml
      #    coverage_report_name: Coverage
      #    coverage_report_title: JaCoCo
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    skip_check_run: false
      #    minimum_coverage: 80
      #    fail_below_threshold: false
      #    publish_only_summary: false
